apiVersion: v1
kind: Service
metadata:
  name: go-server
  labels:
    app: go-server
    service: go-server
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: go-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-server
  labels:
    account: go-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-v2
  labels:
    app: go-server
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      serviceAccountName: go-server
      containers:
      - name: go-server
        image: docker.io/cmwylie19/go-server-2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---